import type { Metadata } from 'next';
import { Geist_Mono, Roboto } from 'next/font/google';

import { ConvexClientProvider } from '@/app/convexClientProvider';
import './globals.css';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  variable: '--font-roboto',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en' className='h-screen'>
      <body
        className={`${roboto.variable} ${geistMono.variable} antialiased h-full`}
      >
        <ConvexClientProvider>
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
